version: '3.9'

services:
  scraper:
    build: .
    environment:
      CFG_FILE: ${CFG_FILE}
      SLEEP_TIME: ${SLEEP_TIME}
      MONGO_URI: mongodb://root:example@mongo:27017
    volumes:
      - .:/app
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # # mongo-gui
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_SERVER: mongo
  #   depends_on:
  #     - mongo
